#!/bin/bash

if (($# < 1)); then
  echo "No SQIMGFILESIZE provided"
  exit 1
fi

SQIMGFILESIZE=$1

REAL_BYTES_USED_DIVIDED_BY_4K=$((SQIMGFILESIZE/4096))
if  [ $((SQIMGFILESIZE % 4096)) != 0 ]
then
  REAL_BYTES_USED_DIVIDED_BY_4K=$((REAL_BYTES_USED_DIVIDED_BY_4K+1))
fi
REAL_BYTES_USED=$((REAL_BYTES_USED_DIVIDED_BY_4K*4096))

echo $REAL_BYTES_USED