SKYSCRAPER_CONFIG = [
    '[main]\n',
    'unattend="true"\n',
    'verbosity="1"\n'
]

ARTWORK = [
    '<?xml version="1.0" encoding="UTF-8"?>\n',
    '<artwork>\n',
    '\t<output type="cover" resource="cover">\n'
    '\t</output>\n'
    '\t<output type="screenshot" resource="wheel">\n'
    '\t</output>\n'
    '\t<output type="marquee" resource="marquee">\n'
    '\t</output>\n'
    '</artwork>\n'
]

CARTRIDGE_XML = [
    '<?xml version="1.0" encoding="UTF-8"?>\n',
    '<byog_cartridge version="1.0">\n',
    '\t<title>GAME_TITLE</title>\n',
    '\t<desc>GAME_DESCRIPTION</desc>\n',
    '\t<boxart file="boxart\\boxart.png" ext="png">\n',
    '</byog_cartridge>\n',
]

EXEC_SH = [
    '#!/bin/sh\n',
    'set -x\n',
    '/emulator/retroplayer ./emu/CORE_FILE_NAME "./roms/GAME_FILE_NAME"\n'
]

SCRAPE_FLAGS = ['nosubdirs', 'noscreenshots']

GAME_LIST_FLAGS = ['nobrackets', 'skipped', 'symlink', 'videos']

PLATFORMS = {'3do': 'bezelproject-3DO',
             # '3ds',
             'amiga': 'bezelprojectSA-Amiga',
             'amigacd32': 'bezelproject-CD32',
             'amstradcpc': 'bezelprojectSA-AmstradCPC',
             # 'apple2',
             'arcade': 'bezelproject-MAME',
             # 'arcadia',
             # 'astrocde',
             'atari800': 'bezelprojectSA-Atari800',
             'atari2600': 'bezelproject-Atari2600',
             'atari5200': 'bezelproject-Atari5200',
             'atari7800': 'bezelproject-Atari7800',
             'atarijaguar': 'bezelproject-AtariJaguar',
             'atarilynx': 'bezelproject-AtariLynx',
             'atarist': 'bezelprojectSA-AtariST',
             # 'c16',
             'c64': 'bezelproject-C64',
             # 'c128',
             # 'coco',
             'coleco': 'bezelproject-ColecoVision',
             'daphne': 'bezelproject-Daphne',
             # 'dragon32',
             'dreamcast': 'bezelproject-Dreamcast',
             'fba': 'bezelproject-MAME',
             'fds': 'bezelproject-MAME',
             # 'gameandwatch',
             'gamegear': 'bezelproject-GameGear',
             'gb': 'bezelproject-GB',
             'gba': 'bezelproject-GBA',
             'gbc': 'bezelproject-GBC',
             'genesis': 'bezelproject-MegaDrive',
             'intellivision': 'bezelproject-Intellivision',
             'mame-libretro': 'bezelproject-MAME',
             'mastersystem': 'bezelproject-MasterSystem',
             'megacd': 'bezelproject-SegaCD',
             'megadrive': 'bezelproject-MegaDrive',
             'msx': 'bezelprojectSA-MSX',
             'n64': 'bezelproject-N64',
             'nds': 'bezelproject-NDS',
             'neogeo': 'bezelproject-MAME',
             'neogeocd': 'bezelproject-NG-CD',
             'nes': 'bezelproject-NES',
             'ngp': 'bezelproject-NGP',
             'ngpc': 'bezelproject-NGPC',
             # 'oric',
             'pc': 'bezelprojectSA-PC',
             # 'pc88',
             # 'pc98',
             'pcfx': 'bezelproject-PCFX',
             'pcengine': 'bezelproject-PCEngine',
             # 'pokemini',
             'psp': 'bezelprojectSA-PSP',
             'psx': 'bezelproject-PSX',
             'saturn': 'bezelproject-Saturn',
             'scummvm': 'bezelproject-ScummVM',
             'sega32x': 'bezelproject-Sega32X',
             'segacd': 'bezelproject-SegaCD',
             'sg-1000': 'bezelproject-SG-1000',
             'snes': 'bezelproject-SNES',
             # 'ti99',
             # 'trs-80',
             # 'vectrex',
             # 'vic20',
             'videopac': 'bezelproject-Videopac',
             'virtualboy': 'bezelproject-Virtualboy',
             'wonderswan': 'bezelproject-WonderSwan',
             'wonderswancolor': 'bezelproject-WonderSwanColor',
             'x68000': 'bezelprojectSA-X68000',
             # 'x1',
             # 'zmachine',
             'zx81': 'bezelprojectSA-ZX81',
             'zxspectrum': 'bezelprojectSA-ZXSpectrum'
             }

# PLATFORMS = ['3do',
#              '3ds',
#              'amiga',
#              'amigacd32',
#              'amstradcpc',
#              'apple2',
#              'arcade',
#              'arcadia',
#              'astrocde',
#              'atari800',
#              'atari2600',
#              'atari5200',
#              'atari7800',
#              'atarijaguar',
#              'atarilynx',
#              'atarist',
#              'c16',
#              'c64',
#              'c128',
#              'coco',
#              'coleco',
#              'daphne',
#              'dragon32',
#              'dreamcast',
#              'fba',
#              'fds',
#              'gameandwatch',
#              'gamegear',
#              'gb',
#              'gba',
#              'gbc',
#              'genesis',
#              'intellivision',
#              'mame-libretro',
#              'mastersystem',
#              'megacd',
#              'megadrive',
#              'msx',
#              'n64',
#              'nds',
#              'neogeo',
#              'neogeocd',
#              'nes',
#              'ngp',
#              'ngpc',
#              'oric',
#              'pc',
#              'pc88',
#              'pc98',
#              'pcfx',
#              'pcengine',
#              'pokemini',
#              'psp',
#              'psx',
#              'saturn',
#              'scummvm',
#              'sega32x',
#              'segacd',
#              'sg-1000',
#              'snes',
#              'ti99',
#              'trs-80',
#              'vectrex',
#              'vic20',
#              'videopac',
#              'virtualboy',
#              'wonderswan',
#              'wonderswancolor',
#              'x68000',
#              'x1',
#              'zmachine',
#              'zx81',
#              'zxspectrum']

SCRAPING_MODULES = ['screenscraper', 'arcadedb', 'igdb', 'mobygames', 'openretro', 'thegamesdb',
                    'worldofspectrum']
